### PR TITLE
chore: add .nvmrc

### PR DESCRIPTION
**Pull request by manolakis**
## What I did

1. I added the `.nvmrc` file to indicate that node v14 is required in this project

### CODE REVIEW

**Comment by bennypowers** [comment]
can this be a range of "at least v14"? I'm using v15 features in my site

**Comment by manolakis** [comment]
I'm not sure if I'm understanding you. This `.nvmrc` should point to the minimal node version required to build this repo. Your site I guess is in another repo and would require the npm packages of this one, but this `.nvmrc` is not going to affect to your repo. You can have another `.nvmrc` pointing to node v15.

**Comment by bennypowers** [comment]
@manolakis you're right, my mistake

**Comment by daKmoR** [comment]
not sure who will use that file... 🤔 

but we can certainly add it - thx 🤗

**Comment by manolakis** [comment]
I use it! 😅

**Comment by daKmoR** [comment]
> I use it! 😅

how? do you check it manually and then run nvm? or do you run nvm whenever you go into a directory? 🤔

**Comment by manolakis** [comment]
Its automatic. nvm is executed automatically when I enter in a dir o subdir with the file.

**Pull request merged**
